version: "3.9"

services:
    mysql:
        image: mysql:latest
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - mysql-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8008:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: password
        depends_on:
            - mysql

    redis:
        image: redis:latest
        restart: always

volumes:
    mysql-data:
        driver: local
